 
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: job-crm-v1_development
 
test:
  <<: *default
  database: job-crm-v1_test

 
production:
  <<: *default
  database: job-crm-v1_production
  username: job-crm-v1
  password: <%= ENV['JOB-CRM-V1_DATABASE_PASSWORD'] %>
